[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm config set cache /tmp/.npm-cache && npm ci --prefer-offline"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"