-- FFAnalytics Scheduler Database Schema Migration
-- Creates tables for job logging, health monitoring, and alerting

-- Job execution log table
CREATE TABLE IF NOT EXISTS analytics_job_log (
  id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
  job_id VARCHAR(100) NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('success', 'failed', 'running', 'cancelled')),
  trigger VARCHAR(20) NOT NULL CHECK (trigger IN ('automatic', 'manual', 'retry')),
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Health check log table
CREATE TABLE IF NOT EXISTS analytics_health_log (
  id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
  status VARCHAR(20) NOT NULL CHECK (status IN ('healthy', 'degraded', 'unhealthy')),
  details JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alerts table
CREATE TABLE IF NOT EXISTS analytics_alerts (
  id UUID DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  severity VARCHAR(10) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  data JSONB DEFAULT '{}'::jsonb,
  acknowledged BOOLEAN DEFAULT FALSE,
  acknowledged_at TIMESTAMP WITH TIME ZONE,
  acknowledged_by VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_analytics_job_log_status ON analytics_job_log(status);
CREATE INDEX IF NOT EXISTS idx_analytics_job_log_trigger ON analytics_job_log(trigger);
CREATE INDEX IF NOT EXISTS idx_analytics_job_log_created_at ON analytics_job_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_job_log_job_id ON analytics_job_log(job_id);

CREATE INDEX IF NOT EXISTS idx_analytics_health_log_status ON analytics_health_log(status);
CREATE INDEX IF NOT EXISTS idx_analytics_health_log_created_at ON analytics_health_log(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_analytics_alerts_type ON analytics_alerts(type);
CREATE INDEX IF NOT EXISTS idx_analytics_alerts_severity ON analytics_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_analytics_alerts_acknowledged ON analytics_alerts(acknowledged);
CREATE INDEX IF NOT EXISTS idx_analytics_alerts_created_at ON analytics_alerts(created_at DESC);

-- Add comments for documentation
COMMENT ON TABLE analytics_job_log IS 'Logs all FFAnalytics scheduler job executions';
COMMENT ON TABLE analytics_health_log IS 'Logs periodic health checks of the FFAnalytics system';
COMMENT ON TABLE analytics_alerts IS 'Stores alerts generated by the FFAnalytics scheduler';

COMMENT ON COLUMN analytics_job_log.job_id IS 'Unique identifier for each job execution';
COMMENT ON COLUMN analytics_job_log.status IS 'Final status of the job execution';
COMMENT ON COLUMN analytics_job_log.trigger IS 'What triggered the job (automatic schedule, manual, or retry)';
COMMENT ON COLUMN analytics_job_log.details IS 'Additional details about the job execution (duration, errors, etc.)';

COMMENT ON COLUMN analytics_health_log.status IS 'Overall health status of the system';
COMMENT ON COLUMN analytics_health_log.details IS 'Detailed health check results including service statuses';

COMMENT ON COLUMN analytics_alerts.type IS 'Type of alert (update_failed, health_check_failed, etc.)';
COMMENT ON COLUMN analytics_alerts.severity IS 'Severity level of the alert';
COMMENT ON COLUMN analytics_alerts.data IS 'Alert-specific data and context';
COMMENT ON COLUMN analytics_alerts.acknowledged IS 'Whether the alert has been acknowledged by an administrator';